version: '3.4'

services:
    workerservice.worker:
        image: ${DOCKER_REGISTRY-}workerserviceworker
        environment:
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_ENVIRONMENT=Development
            - MessageQueueOptions__HostName=rabbitmq
            - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=postgres;User Id=admin;Password=password;
        ports:
            - "5001:443"
            - "5000:80"
        build:
            context: .
            dockerfile: WorkerService.Worker/Dockerfile
        depends_on:
            - rabbitmq
            - rabbitmq-create-queues
        links: ["rabbitmq", "rabbitmq-create-queues"]
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro